name: Minify and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # Or any other command to install dependencies

      - name: Minify CSS
        run: |
          find css -type f \( ! -path "css/bootstrap/*" ! -name "animate.min.css" \) -name "*.css" -exec sh -c 'npx cssnano "{}" "{}.min.css"' \;

      - name: Minify JavaScript
        run: |
          find js -type f \( ! -path "js/bootstrap/*" ! -name "fslightbox.js" \) -name "*.js" -exec sh -c 'npx uglify-js "{}" -o "{}.min.js"' \;

      # Add more steps as necessary for your build process, such as copying minified files to the appropriate directory

      - name: Commit and push minified files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Minify CSS and JavaScript"
          git push